In [5]:
price_a=[8.70, 8.91, 8.71]

In [2]:
8.91/8.70 - 1

0.024137931034482918

In [3]:
8.71/8.91 -1

-0.022446689113355678

In [7]:
len(price_a)

3

In [10]:
returns=[]
for i in range(len(price_a)-1):
    r=price_a[1:][i]/price_a[:-1][i]-1
    returns.append(r)
print(returns)

[0.024137931034482918, -0.022446689113355678]


In [11]:
import pandas as pd


ModuleNotFoundError: No module named 'pandas'

In [12]:
import numpy as np

In [13]:
np.array(price_a)

array([8.7 , 8.91, 8.71])

In [14]:
price_a[1:]/price_a[:-1]

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [15]:
price_a=np.array([8.7,8.91,9.71])

In [17]:
returns=price_a[1:]/price_a[:-1]-1

In [18]:
print(returns)

[0.02413793 0.08978676]


In [19]:
import pandas as pd

In [22]:
prices=pd.DataFrame({"Blue":[8.7,8.91,8.71,8.43,8.73],
                     "Orange":[10.66, 11.08,10.71,11.59,12.11]})

In [23]:
prices


Blue  Orange
0  8.70   10.66
1  8.91   11.08
2  8.71   10.71
3  8.43   11.59
4  8.73   12.11

In [29]:
p1=prices.iloc[1:]

In [30]:
p2=prices.iloc[:-1]

In [32]:
prices.iloc[1:].values/prices.iloc[:-1].values

array([[1.02413793, 1.03939962],
       [0.97755331, 0.9666065 ],
       [0.96785304, 1.0821662 ],
       [1.03558719, 1.04486626]])

In [34]:
pd.DataFrame(prices.iloc[1:].values/prices.iloc[:-1].values-1)

0         1
0  0.024138  0.039400
1 -0.022447 -0.033394
2 -0.032147  0.082166
3  0.035587  0.044866

In [36]:
prices.values

array([[ 8.7 , 10.66],
       [ 8.91, 11.08],
       [ 8.71, 10.71],
       [ 8.43, 11.59],
       [ 8.73, 12.11]])

In [37]:
prices.shift(1)

Blue  Orange
0   NaN     NaN
1  8.70   10.66
2  8.91   11.08
3  8.71   10.71
4  8.43   11.59

In [38]:
prices.shift(-1)

Blue  Orange
0  8.91   11.08
1  8.71   10.71
2  8.43   11.59
3  8.73   12.11
4   NaN     NaN

In [39]:
prices.pct_change()

Blue    Orange
0       NaN       NaN
1  0.024138  0.039400
2 -0.022447 -0.033394
3 -0.032147  0.082166
4  0.035587  0.044866

In [41]:
prices/prices.shift(1)-1

Blue    Orange
0       NaN       NaN
1  0.024138  0.039400
2 -0.022447 -0.033394
3 -0.032147  0.082166
4  0.035587  0.044866